version: "3.3"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/Nginx.Dockerfile
    ports:
      - 8080:80
    links:
      - fpm
    volumes:
      - ./:/var/www/html
  fpm:
    build:
      context: .
      dockerfile: docker/Fpm.Dockerfile
    volumes:
      - ./:/var/www/html
    links:
      - postgres
  postgres:
    image: postgres:10
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=web_database
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=exchange
  npm:
    image: "node:12"
    working_dir: /var/www/html
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/var/www/html
    entrypoint: ['npm', '--no-bin-links']
    command: bash -c "npm install && npm run dev"